---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ecrgfvbu/public_html/
    ---
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
